# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'iOS_Architecture_OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS_Architecture_OC
  
  # Facebook封装的KVO
  pod 'KVOController'
  # 函数响应式编程框架
  pod 'ReactiveObjC'
  # 提示组件框架
  pod 'SVProgressHUD'
  # 网络请求框架
  pod 'YTKNetwork'
  # AOP面向切面
  pod 'Aspects'
  # 路由组件化解耦
  pod 'JLRoutes'
  # 自动布局
  pod 'Masonry'

  target 'iOS_Architecture_OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_Architecture_OCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
